CREATE TABLE users (
    id INT(11) NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    verification_token VARCHAR(255) DEFAULT NULL,
    is_verified VARCHAR(255) DEFAULT NULL,
    reset_token VARCHAR(255) DEFAULT NULL,
    reset_token_expiry DATETIME DEFAULT NULL,
    verification_code VARCHAR(200) DEFAULT NULL,
    phone VARCHAR(200) DEFAULT NULL,
    country VARCHAR(100) DEFAULT NULL,
    city VARCHAR(100) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    postcode VARCHAR(20) DEFAULT NULL,
    dob DATE DEFAULT NULL,
    twofa_code VARCHAR(6) DEFAULT NULL,
    twofa_expires DATETIME DEFAULT NULL,
    role VARCHAR(20) DEFAULT 'user',
    profile_complete TINYINT(1) DEFAULT 0,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
